import { useParams, Link } from "react-router-dom";
import { ArrowLeft, Calendar, Clock, Share2 } from "lucide-react";
import SEO from "../components/SEO";

// A mock database of blog posts content
const POST_CONTENT = {
  "how-to-compress-pdf-for-email": {
    title: "How to Compress a PDF for Email Attachments",
    date: "June 5, 2026",
    readTime: "3 min read",
    content: `
      ## The Email Attachment Problem
      We've all been there. You try to send an important document, and Gmail stops you with the dreaded "File exceeds 25MB limit" error. 
      
      ## Why are PDFs so big?
      PDFs often contain high-resolution images, embedded fonts, and unoptimized metadata. While great for printing, they are terrible for quick sharing over the internet.

      ## How to fix it instantly
      Instead of using paid software like Adobe Acrobat, you can use our free online PDF Compressor. It strips out unnecessary metadata and applies lossless compression to your images.
      
      1. Go to our [PDF Tools](/pdf-tools) page.
      2. Upload your bulky PDF file.
      3. Click 'Process' and instantly download a smaller file without sacrificing visual quality!
    `
  },
  "convert-images-to-webp-guide": {
    title: "Why You Should Convert All Your Images to WebP",
    date: "June 2, 2026",
    readTime: "5 min read",
    content: `
      ## What is WebP?
      WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster.

      ## JPEG vs WebP
      WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent SSIM quality index.

      ## How to Convert
      You can easily convert any JPEG or PNG to WebP using our free [Image Tools](/image-tools). Select the 'Convert' tab, choose your target format as WebP, and get your optimized image instantly.
    `
  },
  "secure-passwords-best-practices": {
    title: "The Ultimate Guide to Generating Secure Passwords",
    date: "May 28, 2026",
    readTime: "4 min read",
    content: `
      ## The Problem with Human Passwords
      Humans are predictable. We use our birthdays, pet names, and the classic "Password123". Hackers know this and use dictionary attacks to crack these within seconds.

      ## What makes a password secure?
      A secure password should be completely random, generated by a machine, and long enough to withstand brute-force attacks (at least 16 characters).

      ## Use our Local Generator
      Our [Dev Tools](/dev-tools) include a highly secure Password Generator. It uses the Web Crypto API, meaning the password is generated locally in your browser and never sent over the internet.
    `
  }
};

export default function BlogPost() {
  const { slug } = useParams();
  const post = POST_CONTENT[slug];

  if (!post) {
    return (
      <div className="text-center py-24">
        <h1 className="text-3xl font-bold text-slate-800 mb-4">Post not found</h1>
        <Link to="/blog" className="text-blue-500 hover:underline">Return to Blog</Link>
      </div>
    );
  }

  // Simple Markdown-to-HTML parser for mock content
  const renderContent = (markdown) => {
    return markdown.split('\n').map((line, idx) => {
      const t = line.trim();
      if (t.startsWith('## ')) return <h2 key={idx} className="text-2xl font-bold text-slate-800 mt-8 mb-4">{t.replace('## ', '')}</h2>;
      if (t.match(/^[0-9]+\./)) return <li key={idx} className="ml-6 list-decimal text-slate-600 mb-2">{t.replace(/^[0-9]+\./, '').trim()}</li>;
      if (t.length > 0) return <p key={idx} className="text-slate-600 leading-relaxed mb-4" dangerouslySetInnerHTML={{ __html: t.replace(/\[(.*?)\]\((.*?)\)/g, '<a href="$2" class="text-blue-500 font-semibold hover:underline">$1</a>') }}></p>;
      return null;
    });
  };

  return (
    <>
      <SEO
        title={`${post.title} | Convertly Blog`}
        description={post.content.substring(0, 150) + "..."}
        url={`/blog/${slug}`}
      />
      
      <div className="max-w-3xl mx-auto py-8">
        <Link to="/blog" className="inline-flex items-center text-sm font-semibold text-slate-500 hover:text-slate-800 transition-colors mb-8">
          <ArrowLeft size={16} className="mr-2" /> Back to all articles
        </Link>
        
        <article className="glass bg-white/70 border border-slate-200/50 p-8 md:p-12 rounded-3xl shadow-sm">
          <header className="mb-10 text-center">
            <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 leading-tight mb-6">{post.title}</h1>
            <div className="flex items-center justify-center gap-6 text-sm font-semibold text-slate-500">
              <span className="flex items-center gap-2"><Calendar size={16} /> {post.date}</span>
              <span className="flex items-center gap-2"><Clock size={16} /> {post.readTime}</span>
            </div>
          </header>
          
          <div className="prose prose-slate max-w-none">
            {renderContent(post.content)}
          </div>
          
          <footer className="mt-12 pt-8 border-t border-slate-200 flex justify-between items-center">
            <div className="font-bold text-slate-800">Share this article</div>
            <button className="flex items-center gap-2 px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-semibold transition-colors">
              <Share2 size={16} /> Share
            </button>
          </footer>
        </article>
      </div>
    </>
  );
}
